apiVersion: cloud.google.com/v1
kind: ComputeClass
metadata:
  name: ai-compute
spec:
  priorities:
  - machineFamily: n1
    gpu:
      type: nvidia-tesla-t4
      count: 1
    flexStart:
      enabled: true
      nodeRecycling:
        leadTimeSeconds: 3600
  - machineFamily: n1
    gpu:
      type: nvidia-tesla-t4
      count: 1
    spot: true
